runtime: nodejs20

# Environment variables
# IMPORTANT: Replace these with your actual values
env_variables:
  NODE_ENV: "production"
  
  # MongoDB connection string
  MONGODB_URI: "mongodb+srv://linxuanc_db_user:csci571webtechnologies@csci571.pza8miz.mongodb.net/eventsDB?retryWrites=true&w=majority&appName=CSCI571"
  
  # Ticketmaster API Key
  TICKETMASTER_API_KEY: "jojFIRo2FHGGqS1uAjnQIfKPuCzdGYz1"
  
  # Spotify API credentials
  SPOTIFY_CLIENT_ID: "b3b32ed130f34a8fa37ccad54c74f86a"
  SPOTIFY_CLIENT_SECRET: "33cad56321284f7fabfdeb9eacb3cfee"

# Request handlers
handlers:
  # All requests go to the Node.js app
  - url: /.*
    script: auto
    secure: always

# Instance class (F1 is free tier)
instance_class: F1

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 5
  min_idle_instances: 0
  max_idle_instances: 1
  target_cpu_utilization: 0.65

# Health checks
readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2